# graph_scripts/05_unequal_burden.R

# Line graph showing concentration of suspensions among a small share of schools.


suppressPackageStartupMessages({
  library(dplyr)
  library(ggplot2)
  library(glue)
  library(here)
  library(scales)
  library(ggrepel)
})

source(here::here("graph_scripts", "graph_utils.R"))

calc_top_share <- function(df, label, top_frac = 0.10) {
  df %>%
    dplyr::group_by(academic_year) %>%
    dplyr::group_modify(~{
      school_totals <- .x %>%
        dplyr::group_by(school_code) %>%
        dplyr::summarise(total_susp = sum(total_suspensions, na.rm = TRUE), .groups = "drop") %>%
        dplyr::filter(!is.na(total_susp)) %>%
        dplyr::arrange(dplyr::desc(total_susp))
      n_schools <- nrow(school_totals)
      if (n_schools == 0) {
        return(tibble::tibble())
      }
      top_n <- max(1, floor(top_frac * n_schools))
      total_sum <- sum(school_totals$total_susp, na.rm = TRUE)
      top_sum <- sum(school_totals$total_susp[seq_len(top_n)], na.rm = TRUE)
      tibble::tibble(
        academic_year = unique(.x$academic_year),
        setting = label,
        top_share = safe_div(top_sum, total_sum),
        top_schools = top_n,
        total_schools = n_schools
      )
    }) %>%
    dplyr::ungroup()
}

joined <- load_joined_data()

susp_base <- joined %>%
  dplyr::filter(
    is_traditional,
    subgroup %in% c("All Students", "Total"),
    !is.na(total_suspensions),
    total_suspensions >= 0
  ) %>%
  dplyr::mutate(academic_year = as.character(academic_year))

level_specs <- tibble::tibble(
  school_level = c("Elementary", "Middle", "High"),
  label = c(
    "Elementary Traditional Schools",
    "Middle Traditional Schools",
    "High Traditional Schools"
  ),
  short_name = c("Elementary", "Middle", "High")
)

series_list <- lapply(seq_len(nrow(level_specs)), function(i) {
  level_name <- level_specs$school_level[i]
  label_name <- level_specs$label[i]
  level_data <- susp_base %>% dplyr::filter(school_level == level_name)
  calc_top_share(level_data, label_name)
})

series <- dplyr::bind_rows(series_list)

year_levels <- sort(unique(series$academic_year))
level_order <- level_specs$label

series <- series %>%
  dplyr::mutate(
    academic_year = factor(academic_year, levels = year_levels),
    
    setting = factor(setting, levels = level_order)
  ) %>%
  dplyr::arrange(academic_year, setting) %>%
  dplyr::filter(!is.na(top_share))

latest_year <- latest_year_available(series$academic_year)
palette_levels <- setting_palette[level_order]
palette_levels <- palette_levels[!is.na(palette_levels)]

plot_all_years <- ggplot(series,
                         aes(x = academic_year, y = top_share, fill = setting)) +
  geom_col(position = position_dodge(width = 0.75), width = 0.65) +
  geom_text(
    aes(label = scales::percent(top_share, accuracy = 0.1)),
    position = position_dodge(width = 0.75),
    vjust = -0.25,
    size = 3
  ) +
  scale_fill_manual(values = palette_levels, name = NULL, drop = FALSE) +
  scale_y_continuous(
    labels = scales::percent_format(accuracy = 0.1),
    expand = expansion(mult = c(0, 0.08))
  ) +
  coord_cartesian(clip = "off") +
  labs(
    title = "Suspensions Concentrate in a Handful of Schools",
    subtitle = "Share of total suspensions attributed to the top 10% of traditional schools, by level",
    x = NULL,
    y = "Share of suspensions",
    caption = "Source: California statewide suspension data (susp_v5 + v6 features)"
  ) +

  guides(fill = guide_legend(nrow = 1)) +
  theme_reach()

out_path_all <- file.path(OUTPUT_DIR, "unequal_burden_levels_by_year.png")

if (nrow(series) > 0) {
  ggsave(out_path_all, plot_all_years, width = 11.5, height = 7, dpi = 320)
}

series_latest <- series %>%
  dplyr::filter(as.character(academic_year) == latest_year)

out_path_latest <- file.path(OUTPUT_DIR, "unequal_burden_levels_latest.png")

if (nrow(series_latest) > 0) {
  latest_order <- as.character(series_latest$setting)
  series_latest <- series_latest %>%
    dplyr::mutate(setting = factor(as.character(setting), levels = latest_order))
  palette_latest <- palette_levels[as.character(levels(series_latest$setting))]

  plot_latest <- ggplot(series_latest,
                        aes(x = setting, y = top_share, fill = setting)) +
    geom_col(width = 0.6) +
    geom_text(
      aes(label = scales::percent(top_share, accuracy = 0.1)),
      vjust = -0.25,
      size = 3
    ) +
    scale_fill_manual(values = palette_latest, guide = "none") +
    scale_y_continuous(
      labels = scales::percent_format(accuracy = 0.1),
      expand = expansion(mult = c(0, 0.12))
    ) +
    coord_cartesian(clip = "off") +
    labs(
      title = glue("Suspension Concentration in {latest_year}"),
      subtitle = "Share of suspensions generated by the top 10% of traditional schools",
      x = NULL,
      y = "Share of suspensions",
      caption = "Source: California statewide suspension data (susp_v5 + v6 features)"
    ) +
    theme_reach() +
    theme(axis.text.x = element_text(angle = 0, hjust = 0.5))

  ggsave(out_path_latest, plot_latest, width = 8, height = 6, dpi = 320)
}


fmt_percent <- function(x) if (!is.na(x)) scales::percent(x, accuracy = 0.1) else "N/A"

first_year <- if (length(year_levels) > 0) year_levels[1] else NA_character_


pull_series_value <- function(setting_name, year_value, column) {
  if (is.na(year_value)) {
    return(NA)
  }

  filtered <- series %>%
    dplyr::filter(
      setting == setting_name,
      as.character(academic_year) == year_value
    )

  if (nrow(filtered) == 0) {
    return(NA)
  }

  val <- dplyr::pull(filtered, column)
  if (length(val) == 0) NA else val[1]
}

shares_latest <- sapply(level_specs$label, function(lbl) pull_series_value(lbl, latest_year, "top_share"))
shares_first  <- sapply(level_specs$label, function(lbl) pull_series_value(lbl, first_year, "top_share"))
top_counts_latest   <- sapply(level_specs$label, function(lbl) pull_series_value(lbl, latest_year, "top_schools"))
total_counts_latest <- sapply(level_specs$label, function(lbl) pull_series_value(lbl, latest_year, "total_schools"))

latest_year_phrase <- if (!is.na(latest_year)) latest_year else "the latest year available"

level_descriptions <- vapply(seq_len(nrow(level_specs)), function(i) {
  latest_share <- shares_latest[i]
  first_share <- shares_first[i]
  top_ct <- top_counts_latest[i]
  total_ct <- total_counts_latest[i]

  desc <- glue(
    "{level_specs$short_name[i]} schools: the top 10% accounted for {fmt_percent(latest_share)} of suspensions in {latest_year_phrase}"
  )

  if (!is.na(first_year) && !is.na(first_share) && first_year != latest_year) {
    desc <- glue("{desc}, compared with {fmt_percent(first_share)} in {first_year}")
  }

  if (!is.na(top_ct) && !is.na(total_ct)) {
    glue("{desc}, meaning roughly {top_ct} of {total_ct} campuses.")
  } else {
    glue("{desc}.")
  }
}, character(1))

level_descriptions <- level_descriptions[!is.na(level_descriptions) & trimws(level_descriptions) != ""]

trend_phrase <- ""
if (!is.na(first_year) && !is.na(latest_year) && first_year != latest_year) {
  trend_phrase <- glue("Trends span {first_year} through {latest_year}.")
} else if (!is.na(latest_year)) {
  trend_phrase <- glue("Latest results reflect {latest_year}.")
}

intro_parts <- c("Suspensions remain highly concentrated within a small share of traditional campuses.")
if (nzchar(trend_phrase)) {
  intro_parts <- c(intro_parts, trend_phrase)
}

concentration_text <- paste(c(intro_parts, level_descriptions), collapse = " ")

write_description(concentration_text, "unequal_burden_levels.txt")

if (nrow(series_latest) > 0) {
  message("Saved plots to ", out_path_all, " and ", out_path_latest)
} else {
  message("Saved plot to ", out_path_all)
}
