# R/check_teacher_race_columns.R
# Quick diagnostic to confirm that the staged teacher files include
# race/ethnicity breakdowns required for downstream diversity analyses.

suppressPackageStartupMessages({
  library(arrow)
  library(dplyr)
  library(here)
  library(janitor)
  library(tibble)
})

source(here::here("R", "teacher_processing.R"))

#' Verify that staged teacher datasets contain race/ethnicity columns.
#'
#' @param teacher_long_path Path to the long-form teacher parquet generated by
#'   `R/01c_ingest_teacher_demographics.R`.
#' @param merged_features_path Optional path to the merged student + teacher
#'   features parquet (`Analysis/18_merge_teacher_student.R`). When present, the
#'   function confirms that the merged file also exposes the race columns.
#' @return A list containing the discovered columns so callers can use the
#'   results programmatically. Messages are printed for interactive use.
verify_teacher_race_columns <- function(
    teacher_long_path = here::here("data-stage", "teacher_staff_long.parquet"),
    merged_features_path = here::here("data-stage", "susp_v6_teacher_features.parquet")
) {
  if (!file.exists(teacher_long_path)) {
    stop("Teacher parquet not found at ", teacher_long_path,
         "\nRun R/01c_ingest_teacher_demographics.R after copying stre*.txt files to data-raw/.")
  }

  message("[teacher-check] Reading ", teacher_long_path)
  teacher_long <- arrow::read_parquet(teacher_long_path) |> janitor::clean_names()

  message("[teacher-check] Summarising teacher data to wide format ...")
  teacher_summary <- teacher_summarise_long(teacher_long)

  race_keywords <- c(
    "african", "black", "american_indian", "asian", "filipino",
    "hispanic", "latino", "pacific", "hawaiian", "white",
    "two_or_more", "not_reported"
  )
  race_pattern <- paste(race_keywords, collapse = "|")
  all_race_cols <- grep("^teacher_staff_count_", names(teacher_summary), value = TRUE)
  race_cols <- all_race_cols[grepl(race_pattern, all_race_cols)]
  race_count_cols <- race_cols[
    !grepl("_share$", race_cols) &
      !grepl("_by_type_", race_cols) &
      !grepl("_by_gender_", race_cols)
  ]
  race_share_cols <- race_cols[grepl("_share$", race_cols)]
  race_share_cols <- race_share_cols[
    !grepl("_by_type_", race_share_cols) &
      !grepl("_by_gender_", race_share_cols)
  ]

  if (!length(race_count_cols)) {
    stop(
      "[teacher-check] Race/ethnicity counts missing in teacher summary.\n",
      "Expected columns such as 'teacher_staff_count_african_american'.\n",
      "Confirm the stre*.txt files include race detail and rerun the ingestion script."
    )
  }

  message("[teacher-check] ✔ Found ", length(race_count_cols), " race count columns in teacher summary.")
  message("                 Examples: ", paste(head(race_count_cols, 5), collapse = ", "))

  if (length(race_share_cols)) {
    message("[teacher-check] ✔ Found ", length(race_share_cols), " race share columns.")
  } else {
    message("[teacher-check] ⚠ Race share columns not detected. Shares are derived in downstream scripts.")
  }

  merged_cols <- character()
  if (file.exists(merged_features_path)) {
    message("[teacher-check] Reading merged student + teacher features: ", merged_features_path)
    merged_df <- arrow::read_parquet(merged_features_path, as_data_frame = FALSE)
    merged_names <- names(merged_df)
    merged_cols <- intersect(race_count_cols, merged_names)

    if (!length(merged_cols)) {
      warning(
        "[teacher-check] Race columns not present in ", basename(merged_features_path),
        " even though they exist in the teacher summary.\n",
        "Re-run Analysis/18_merge_teacher_student.R to pull the new fields into the merged dataset."
      )
    } else {
      message("[teacher-check] ✔ Merged dataset includes ", length(merged_cols), " race columns.")
    }
  } else {
    message(
      "[teacher-check] Skipping merged feature check; file not found at ",
      merged_features_path
    )
  }

  invisible(list(
    teacher_race_count_columns = race_count_cols,
    teacher_race_share_columns = race_share_cols,
    merged_race_columns = merged_cols
  ))
}

# Allow script to run directly via `Rscript R/check_teacher_race_columns.R`.
if (identical(environmentName(environment()), "R_GlobalEnv")) {
  tryCatch(
    verify_teacher_race_columns(),
    error = function(e) {
      message("[teacher-check] ERROR: ", conditionMessage(e))
      quit(status = 1)
    }
  )
}
